#---------------------------------------------------
#General Parameters 
#---------------------------------------------------
ALL: "neurog2"
SAMPLES: "samples.tsv"
ANNOFILE: "annotations.txt"
MARKERS: "mouse_markers.txt"
